# Generated by Django 5.0.6 on 2026-03-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_card_due_date_change_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cardduedatechangerequest',
            new_name='projects_ca_status_3c7cbf_idx',
            old_name='projects_ca_status_9626e9_idx',
        ),
        migrations.RenameIndex(
            model_name='cardduedatechangerequest',
            new_name='projects_ca_card_id_f4eb23_idx',
            old_name='projects_ca_card_i_480b21_idx',
        ),
        migrations.RenameIndex(
            model_name='cardduedatechangerequest',
            new_name='projects_ca_request_a0f80a_idx',
            old_name='projects_ca_request_a7301e_idx',
        ),
    ]
