# Generated by Django 5.0.6 on 2026-03-18 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_rename_projects_ca_status_9626e9_idx_projects_ca_status_3c7cbf_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Key (status)')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='Etapa Terminal')),
                ('requires_required_data', models.BooleanField(default=False, verbose_name='Requer Dados Obrigatórios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Etapa do Kanban',
                'verbose_name_plural': 'Etapas do Kanban',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ProjectKanbanStageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_stage_configs', to='projects.project', verbose_name='Projeto')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_configs', to='projects.kanbanstage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Configuração de Etapas do Kanban por Projeto',
                'verbose_name_plural': 'Configurações de Etapas do Kanban por Projeto',
                'ordering': ['order', 'stage__key'],
                'unique_together': {('project', 'stage')},
            },
        ),
    ]
