# Generated by Django 5.0.6 on 2026-04-08 19:27

from datetime import datetime, time

from django.db import migrations, models
from django.utils import timezone


def _aware_start_of_day(dt_or_d):
    if hasattr(dt_or_d, "hour"):
        di = dt_or_d
        if timezone.is_naive(di):
            return timezone.make_aware(di, timezone.get_current_timezone())
        return di
    return timezone.make_aware(datetime.combine(dt_or_d, time.min), timezone.get_current_timezone())


def forwards_fix_naive_inicio(apps, schema_editor):
    Sprint = apps.get_model("projects", "Sprint")
    for s in Sprint.objects.all().only("id", "data_inicio"):
        di = s.data_inicio
        if di is None:
            continue
        fixed = _aware_start_of_day(di)
        if fixed != di:
            Sprint.objects.filter(pk=s.pk).update(data_inicio=fixed)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_sprint_fechamento_em_remove_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Data e hora de início'),
        ),
        migrations.RunPython(forwards_fix_naive_inicio, migrations.RunPython.noop),
    ]
