# Generated by Django 5.0.6 on 2026-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_card_finalizado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlog',
            name='tipo_evento',
            field=models.CharField(choices=[('criado', 'Card Criado'), ('movimentado', 'Movimentado'), ('pendencia', 'Pendência'), ('atualizado', 'Atualizado'), ('alteracao', 'Alteração no Card'), ('responsavel_alterado', 'Responsável Alterado'), ('comentario', 'Comentário')], max_length=30, verbose_name='Tipo de Evento'),
        ),
    ]
