# Generated by Django 5.0.6 on 2026-05-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_alter_cardlog_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='links',
            field=models.JSONField(blank=True, default=list, help_text='Lista de links extras: [{"url": "...", "label": "..."}]', verbose_name='Links adicionais'),
        ),
    ]
