# Generated by Django 5.2.10 on 2026-05-13 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_cardduedatechangerequest_requested_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('card_created', 'Card Criado'), ('card_updated', 'Card Atualizado'), ('card_deleted', 'Card Deletado'), ('card_moved', 'Card Movido'), ('sprint_created', 'Sprint Criada'), ('project_created', 'Projeto Criado'), ('role_changed', 'Cargo Alterado'), ('card_overdue', 'Card Atrasado'), ('card_due_24h', 'Card Vence em 24h'), ('card_due_1h', 'Card Vence em 1h'), ('card_due_10min', 'Card Vence em 10min'), ('log_created', 'Log Criado')], max_length=30, verbose_name='Tipo de Notificação'),
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_updated', models.BooleanField(default=True, verbose_name='Cards atualizados')),
                ('card_deleted', models.BooleanField(default=True, verbose_name='Cards deletados')),
                ('project_created', models.BooleanField(default=True, verbose_name='Projetos criados')),
                ('card_overdue', models.BooleanField(default=True, verbose_name='Cards atrasados')),
                ('card_due_24h', models.BooleanField(default=True, verbose_name='Vencimento em 24h')),
                ('card_due_1h', models.BooleanField(default=True, verbose_name='Vencimento em 1h')),
                ('card_due_10min', models.BooleanField(default=True, verbose_name='Vencimento em 10min')),
                ('card_created', models.BooleanField(default=False, verbose_name='Cards criados')),
                ('card_moved', models.BooleanField(default=False, verbose_name='Cards movidos')),
                ('sprint_created', models.BooleanField(default=False, verbose_name='Sprints criadas')),
                ('role_changed', models.BooleanField(default=False, verbose_name='Mudanças de cargo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência de notificação',
                'verbose_name_plural': 'Preferências de notificação',
            },
        ),
    ]
