# Generated by Django 5.2.10 on 2026-05-13 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_alter_notification_tipo_usernotificationpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('body', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('color', models.CharField(choices=[('default', 'Padrão'), ('red', 'Vermelho'), ('orange', 'Laranja'), ('yellow', 'Amarelo'), ('green', 'Verde'), ('teal', 'Verde-água'), ('blue', 'Azul'), ('purple', 'Roxo'), ('pink', 'Rosa'), ('gray', 'Cinza')], default='default', max_length=20, verbose_name='Cor')),
                ('pinned', models.BooleanField(default=False, verbose_name='Fixada')),
                ('archived', models.BooleanField(default=False, verbose_name='Arquivada')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-pinned', 'order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNoteTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500, verbose_name='Texto')),
                ('done', models.BooleanField(default=False, verbose_name='Concluído')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='projects.usernote', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Item de nota',
                'verbose_name_plural': 'Itens de nota',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CardTodo',
        ),
        migrations.AddIndex(
            model_name='usernote',
            index=models.Index(fields=['user', 'archived', '-updated_at'], name='projects_us_user_id_9734ed_idx'),
        ),
        migrations.AddIndex(
            model_name='usernote',
            index=models.Index(fields=['user', 'pinned', '-updated_at'], name='projects_us_user_id_f8edbf_idx'),
        ),
    ]
