# Generated by Django 5.2.10 on 2026-05-13 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_remove_cardtodo_add_usernote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fixado em')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='projects.card', verbose_name='Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_cards', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Card fixado',
                'verbose_name_plural': 'Cards fixados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='projects_ca_user_id_49d3c2_idx')],
                'unique_together': {('user', 'card')},
            },
        ),
    ]
