# Generated by Django 5.2.10 on 2026-05-18 13:06

from django.db import migrations, models


# Mapeamento dos códigos antigos (red/orange/yellow/green/teal/blue/purple/pink/gray)
# para os 5 novos baseados em papéis Color Plus / Sirio Color. Tonalidades
# escolhidas pela aproximação visual mais próxima.
OLD_TO_NEW = {
    'red': 'rosa',
    'orange': 'bege',
    'yellow': 'bege',
    'green': 'verde',
    'teal': 'verde',
    'blue': 'azul',
    'purple': 'lilas',
    'pink': 'rosa',
    'gray': 'default',
}


def remap_colors_forward(apps, schema_editor):
    UserNote = apps.get_model('projects', 'UserNote')
    for old, new in OLD_TO_NEW.items():
        UserNote.objects.filter(color=old).update(color=new)


def remap_colors_reverse(apps, schema_editor):
    # No-op: a operação inversa não tem como reconstruir 9 cores a partir de 5.
    # Notas ficam nas cores novas, que ainda são valores válidos no schema antigo
    # se algum dia precisar (verde/azul/rosa já existiam como 'green'/'blue'/'pink').
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_add_cardpin'),
    ]

    operations = [
        # 1) Converte os dados existentes antes de trocar as choices.
        migrations.RunPython(remap_colors_forward, remap_colors_reverse),
        # 2) Aplica o novo schema de choices.
        migrations.AlterField(
            model_name='usernote',
            name='color',
            field=models.CharField(choices=[('default', 'Padrão'), ('lilas', 'Lilás (San Francisco)'), ('rosa', 'Rosa (Verona)'), ('verde', 'Verde (Tahiti)'), ('azul', 'Azul (Celeste)'), ('bege', 'Bege (Paglierino)')], default='default', max_length=20, verbose_name='Cor'),
        ),
    ]
