# Generated by Django 5.2.10 on 2026-05-18 14:04

import django.db.models.deletion
from django.db import migrations, models


def migrate_old_to_items(apps, schema_editor):
    """Converte cada UserNote (body + UserNoteTodo[]) em uma sequência de
    UserNoteItem ordenada: primeiro o bloco de texto (se body não-vazio),
    depois os antigos todos preservando a ordem original.
    """
    UserNote = apps.get_model('projects', 'UserNote')
    UserNoteTodo = apps.get_model('projects', 'UserNoteTodo')
    UserNoteItem = apps.get_model('projects', 'UserNoteItem')

    for note in UserNote.objects.all().iterator():
        cursor = 0
        body = (note.body or '').strip()
        if body:
            UserNoteItem.objects.create(
                note=note, kind='text', text=body, done=False, order=cursor,
            )
            cursor += 1
        for todo in UserNoteTodo.objects.filter(note=note).order_by('order', 'created_at'):
            UserNoteItem.objects.create(
                note=note, kind='todo', text=todo.label, done=todo.done, order=cursor,
            )
            cursor += 1


def migrate_items_back(apps, schema_editor):
    """Reversão best-effort: concatena items.text como body e recria UserNoteTodos.
    Algo de fidelidade é perdido (textos intercalados viram um body só), mas
    permite voltar a 0039 se necessário."""
    UserNote = apps.get_model('projects', 'UserNote')
    UserNoteTodo = apps.get_model('projects', 'UserNoteTodo')
    UserNoteItem = apps.get_model('projects', 'UserNoteItem')

    for note in UserNote.objects.all().iterator():
        items = list(UserNoteItem.objects.filter(note=note).order_by('order'))
        body_parts = [i.text for i in items if i.kind == 'text']
        note.body = '\n\n'.join(body_parts)
        note.save(update_fields=['body'])
        for idx, item in enumerate(i for i in items if i.kind == 'todo'):
            UserNoteTodo.objects.create(
                note=note, label=item.text, done=item.done, order=idx,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_remap_usernote_colors'),
    ]

    operations = [
        # 1. Cria UserNoteItem (UserNoteTodo e body ainda existem).
        migrations.CreateModel(
            name='UserNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Texto'), ('todo', 'Item de lista')], default='text', max_length=10, verbose_name='Tipo')),
                ('text', models.TextField(blank=True, verbose_name='Texto')),
                ('done', models.BooleanField(default=False, verbose_name='Concluído (só p/ kind=todo)')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.usernote', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Item de nota',
                'verbose_name_plural': 'Itens de nota',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usernoteitem',
            index=models.Index(fields=['note', 'order'], name='projects_us_note_id_60ac8b_idx'),
        ),
        # 2. Copia dados de body + UserNoteTodo → UserNoteItem.
        migrations.RunPython(migrate_old_to_items, migrate_items_back),
        # 3. Agora pode remover o body e o model antigo.
        migrations.RemoveField(
            model_name='usernote',
            name='body',
        ),
        migrations.DeleteModel(
            name='UserNoteTodo',
        ),
    ]
