# Generated by Django 5.2.10 on 2026-05-20 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_usernote_items_blocks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='arquivado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Arquivado'),
        ),
        migrations.AddField(
            model_name='project',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em'),
        ),
        migrations.AddField(
            model_name='project',
            name='arquivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_arquivados', to=settings.AUTH_USER_MODEL, verbose_name='Arquivado por'),
        ),
    ]
