# Generated by Django 5.2.10 on 2026-05-28 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_project_is_system_and_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernoteitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.usernoteitem', verbose_name='Item pai (para indentação)'),
        ),
        migrations.AddIndex(
            model_name='usernoteitem',
            index=models.Index(fields=['parent'], name='projects_us_parent__a9e284_idx'),
        ),
    ]
