# Generated by Django 5.2.10 on 2026-07-03 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_card_segundos_corridos_desenvolvimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Critério')),
                ('peso', models.DecimalField(decimal_places=2, default=0, help_text='Peso do critério na fórmula do Score (ex.: 0.30)', max_digits=5, verbose_name='Peso')),
                ('negativo', models.BooleanField(default=False, help_text='Se marcado, o critério subtrai do Score em vez de somar', verbose_name='Negativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Critério de Score',
                'verbose_name_plural': 'Critérios de Score',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CardScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_solicitante', models.CharField(blank=True, choices=[('fiscal', 'Fiscal'), ('contabil', 'Contábil'), ('marketing', 'Marketing'), ('legalizacao', 'Legalização'), ('pessoal', 'Pessoal'), ('diretoria', 'Diretoria'), ('novos_negocios', 'Novos Negócios'), ('rh', 'RH')], max_length=30, null=True, verbose_name='Setor Solicitante')),
                ('score_final', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Score Final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='projects.card', verbose_name='Card')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Score do Card',
                'verbose_name_plural': 'Scores dos Cards',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreCriterionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='projects.scorecriterion', verbose_name='Critério')),
            ],
            options={
                'verbose_name': 'Opção de Critério',
                'verbose_name_plural': 'Opções de Critério',
                'ordering': ['ordem', 'valor'],
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criado', 'Score Criado'), ('editado', 'Score Editado'), ('excluido', 'Score Excluído')], max_length=20, verbose_name='Ação')),
                ('score_final', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('setor_solicitante', models.CharField(blank=True, max_length=30, null=True)),
                ('snapshot', models.JSONField(blank=True, default=list, help_text='Cópia dos critérios/valores no momento da alteração', verbose_name='Snapshot')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_historico', to='projects.card', verbose_name='Card')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_historico_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Score',
                'verbose_name_plural': 'Históricos de Score',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='CardScoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('card_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='projects.cardscore', verbose_name='Score')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_atribuidos', to='projects.scorecriterion', verbose_name='Critério')),
            ],
            options={
                'verbose_name': 'Valor de Critério do Score',
                'verbose_name_plural': 'Valores de Critério do Score',
                'unique_together': {('card_score', 'criterion')},
            },
        ),
    ]
