# Generated by Django 5.2.10 on 2026-07-08 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_seed_score_criterios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='card_anexos/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome original')),
                ('tamanho', models.PositiveBigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='projects.card', verbose_name='Card')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_anexos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo do card',
                'verbose_name_plural': 'Anexos dos cards',
                'ordering': ['-criado_em'],
            },
        ),
    ]
