"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Sempre carregar .env da pasta backend (funciona com runserver a partir da raiz do repo ou de backend/)
# encoding=utf-8-sig: remove BOM se o editor gravar "UTF-8 com BOM" (senão USE_POSTGRES não é lido).
# override: em dev (omissão) o .env prevalece sobre o ambiente (IDE).
# Na imagem Docker: DOTENV_OVERRIDE=false para o `env_file` do Compose na VPS sobrepor o .env baked no build.
BASE_DIR = Path(__file__).resolve().parent.parent
_dotenv_override = os.getenv('DOTENV_OVERRIDE', 'true').lower() not in ('0', 'false', 'no')
load_dotenv(BASE_DIR / '.env', override=_dotenv_override, encoding="utf-8-sig")
# Em DEV o `python manage.py runserver` precisa também ler o .env da RAIZ do
# repo (BWA_Tech/.env), onde ficam REDIS_PASSWORD, CELERY_BROKER_URL e demais
# valores compartilhados entre serviços do docker-compose. NÃO sobrescreve o
# backend/.env (carregado acima): apenas preenche variáveis ausentes.
# Em prod, esse .env é injetado pelo Compose via `env_file` e este load é no-op.
load_dotenv(BASE_DIR.parent / '.env', override=False, encoding="utf-8-sig")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Fallback `django-insecure-*` REMOVIDO — produção exige SECRET_KEY no ambiente.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'SECRET_KEY não definida. Configure no .env ou nas variáveis de ambiente. '
        'Gere uma com: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
    )
if SECRET_KEY.startswith('django-insecure-'):
    # Em dev pode ser válido, mas avisamos para evitar uso acidental em prod.
    import warnings
    warnings.warn('SECRET_KEY com prefixo "django-insecure-" detectada. Nunca usar em produção.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS: domínios e hosts permitidos (vírgula). Pelo Traefik o Host costuma ser só o domínio.
# Se expuser a porta 8000 pelo IP público inclua também a forma com porta (ex.: 203.0.113.10:8000).
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# Atrás de Traefik/nginx com TLS — define BEHIND_HTTPS_PROXY=true no .env (docker-compose)
_BEHIND_HTTPS_PROXY = os.getenv('BEHIND_HTTPS_PROXY', '').strip().lower() in ('true', '1', 'yes')

# Dev local roda Django nativo no host — não tem proxy reverso na frente.
# Se o hostname `redis` (interno do compose) não resolve, estamos fora do
# compose: força BEHIND_HTTPS_PROXY=False, mesmo que o .env raiz (compartilhado
# com prod) tenha True. Sem isso, SECURE_SSL_REDIRECT redireciona HTTP→HTTPS
# local quebrando preflight CORS (logins via http://localhost:5173 falham).
if _BEHIND_HTTPS_PROXY:
    import socket as _socket
    try:
        _socket.gethostbyname('redis')
    except _socket.gaierror:
        _BEHIND_HTTPS_PROXY = False

if _BEHIND_HTTPS_PROXY:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    # daphne PRECISA vir antes de django.contrib.staticfiles para que `runserver`
    # use o ASGI handler (suporta WebSocket via Channels) em vez do WSGI puro.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    'channels',
    # Local apps
    'apps.accounts',
    'apps.projects',
    'apps.teams',
    'apps.timeline',
    'apps.suggestions',
    'apps.geekday',
    'apps.formularios',
    'apps.reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CSRF protege endpoints baseados em sessão. Endpoints DRF que usam
    # ExpiringTokenAuthentication (header Authorization) ficam isentos de CSRF
    # naturalmente; views públicas (register/login/recover) usam @csrf_exempt.
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for development if PostgreSQL is not available
# .strip(): ficheiros .env no Windows podem trazer \r e impedir USE_POSTGRES=true de ser reconhecido
USE_POSTGRES = os.getenv('USE_POSTGRES', 'False').strip().lower() in ('true', '1', 'yes')

if USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'bwaproj_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# WhiteNoise serve /static/ em produção (admin CSS/JS)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Pasta do build do frontend (npm run build) para servir a SPA em deploy local
FRONTEND_BUILD_DIR = BASE_DIR.parent / 'frontend' / 'dist'

# Media files (uploads). URL com barra no início para montar URLs absolutas corretas.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.accounts.authentication.ExpiringTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Rate limiting (proteção contra brute force / spam / enumeration).
    # Escopos customizados ativados explicitamente em login/register/recover/recovery-attempt.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Limites generosos para evitar bloquear o app legítimo. Endpoints sensíveis
        # (login/register/recovery) têm escopos próprios mais restritos abaixo.
        'anon': '120/min',
        'user': '1200/min',
        'login': '10/min',
        'register': '5/min',
        'recovery': '5/hour',
    },
}

# CORS configuration
# Em produção: CORS_ALLOWED_ORIGINS=https://tech.bwa.global
_dev_origins = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:5175",
    "http://127.0.0.1:5175",
]
_env_origins = [o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]
# Em DEBUG OU rodando fora do compose (dev local) inclui origens de dev.
# `_BEHIND_HTTPS_PROXY` aqui já foi reavaliado acima — se está True, é prod
# real (atrás de Traefik). Senão é dev local mesmo com DEBUG=False herdado
# do .env raiz.
_IS_DEV_RUNTIME = DEBUG or not _BEHIND_HTTPS_PROXY
if _IS_DEV_RUNTIME:
    CORS_ALLOWED_ORIGINS = list(dict.fromkeys(_dev_origins + _env_origins))
else:
    if not _env_origins:
        raise ImproperlyConfigured(
            'CORS_ALLOWED_ORIGINS é obrigatório em produção (BEHIND_HTTPS_PROXY=true). '
            'Defina no .env: CORS_ALLOWED_ORIGINS=https://tech.bwa.global'
        )
    CORS_ALLOWED_ORIGINS = list(dict.fromkeys(_env_origins))

CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'Authorization']
# Cache de preflight CORS no browser. Em dev manter baixo (60s) porque o
# browser cacheia decisões "negativas" também — uma vez que o backend
# respondeu sem header CORS (ex.: redirect 301 antes de algum fix), o navegador
# bloqueia requests por 24h sem refazer preflight. Em prod, 24h é OK (origem é
# estável). Reaproveita o mesmo flag `_IS_DEV_RUNTIME` calculado acima.
CORS_PREFLIGHT_MAX_AGE = 60 if _IS_DEV_RUNTIME else 86400

# CSRF configuration (em produção incluir origens HTTPS do domínio)
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()] or [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:5175",
    "http://127.0.0.1:5175",
]

# Session configuration
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # Permitir que o front acesse se necessário
SESSION_COOKIE_SECURE = os.getenv(
    'SESSION_COOKIE_SECURE',
    'true' if _BEHIND_HTTPS_PROXY else 'false',
).lower() in ('true', '1', 'yes')
CSRF_COOKIE_SECURE = os.getenv(
    'CSRF_COOKIE_SECURE',
    'true' if _BEHIND_HTTPS_PROXY else 'false',
).lower() in ('true', '1', 'yes')

# Security headers (atrás de HTTPS) — Traefik faz o offload de TLS.
if _BEHIND_HTTPS_PROXY and not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'DENY'

# Language and Timezone
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'

# Portal externo — JWT (`access`) para consumir APIs do portal (ex.: formulários em produção).
# Defina apenas em ambiente / backend/.env; não commitar credenciais.
PORTAL_BASE_URL = os.getenv('PORTAL_BASE_URL', '').strip().rstrip('/')
PORTAL_USERNAME = os.getenv('PORTAL_USERNAME', '').strip()
PORTAL_PASSWORD = os.getenv('PORTAL_PASSWORD', '')

# Channels — em Docker com Redis use CHANNEL_LAYER_BACKEND=redis (ver docker-compose.yml)
if os.getenv('CHANNEL_LAYER_BACKEND', '').strip().lower() == 'redis':
    _rh = os.getenv('CHANNEL_REDIS_HOST', os.getenv('REDIS_HOST', '127.0.0.1')).strip()
    _rp = int(os.getenv('CHANNEL_REDIS_PORT', os.getenv('REDIS_PORT', '6379')).strip() or '6379')
    _rpw = os.getenv('REDIS_PASSWORD', '').strip()
    # Dev local: hostname `redis` do compose não resolve fora dele. Tenta
    # resolver — se falha, força 127.0.0.1 (requer docker-compose.override.yml
    # de dev expondo a porta). Em prod resolve e mantém o hostname interno.
    if _rh == 'redis':
        import socket as _socket
        try:
            _socket.gethostbyname('redis')
        except _socket.gaierror:
            _rh = '127.0.0.1'
    # channels_redis aceita URL como host. Se senha existe, embute-a; caso contrário tupla (host, port).
    if _rpw:
        _hosts = [f'redis://:{_rpw}@{_rh}:{_rp}/0']
    else:
        _hosts = [(_rh, _rp)]
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': _hosts},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Celery configuration
# Usar Redis se disponível, caso contrário usar broker em memória para desenvolvimento
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
# Quando o processo Django roda NATIVO no host (dev local), o hostname `redis`
# do docker-compose não resolve via DNS. Heurística: tenta resolver — se
# falha, assume dev e reescreve pra 127.0.0.1 (que precisa do redis container
# expondo a porta via docker-compose.override.yml de dev). Em prod, o backend
# roda dentro do compose e `redis` resolve normalmente — URL fica intacta.
if '@redis:' in CELERY_BROKER_URL or '@redis:' in CELERY_RESULT_BACKEND:
    import socket
    try:
        socket.gethostbyname('redis')
    except socket.gaierror:
        CELERY_BROKER_URL = CELERY_BROKER_URL.replace('@redis:', '@127.0.0.1:')
        CELERY_RESULT_BACKEND = CELERY_RESULT_BACKEND.replace('@redis:', '@127.0.0.1:')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# Desabilitar conexão automática ao broker na inicialização (evita erros quando Redis não está rodando)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = False
# Falha rápida se Redis não responder (evita pedidos HTTP presos ao criar sprint com apply_async)
CELERY_BROKER_CONNECTION_TIMEOUT = 3
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_connect_timeout': 3,
    'socket_timeout': 3,
}

# Modo síncrono pra desenvolvimento sem worker. Quando True, .delay() roda
# inline na request (sem fila/broker). Útil em dev local Windows onde subir
# o worker é mais trabalhoso. NUNCA usar em produção (bloqueia request).
CELERY_TASK_ALWAYS_EAGER = os.getenv('CELERY_TASK_ALWAYS_EAGER', 'False').lower() in ('1', 'true', 'yes')
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER

# Beat schedule (só funciona com Celery Beat rodando)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'check-card-deadlines': {
        'task': 'apps.projects.tasks.check_card_deadlines',
        'schedule': 60.0,  # A cada 60 segundos
    },
    'verificar-fechamento-automatico-semana': {
        'task': 'apps.projects.tasks.verificar_fechamento_automatico_semana',
        'schedule': 60.0,  # A cada 60 segundos
    },
    'finalizar-sprints-por-data': {
        'task': 'apps.projects.tasks.finalizar_sprints_por_data',
        # Fallback de segurança (casos em que o agendamento por ETA ao salvar a sprint falhe).
        # O fechamento no instante correto usa Sprint.fechamento_em (não WeeklyPriorityConfig).
        'schedule': 300.0,  # a cada 5 min
    },
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
