# Generated by Django 5.0.6 on 2026-05-06 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuporteMotivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivo de suporte',
                'verbose_name_plural': 'Motivos de suporte',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SuporteTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de suporte',
                'verbose_name_plural': 'Tipos de suporte',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SuporteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='formularios.suportetipo')),
            ],
            options={
                'verbose_name': 'Item de suporte',
                'verbose_name_plural': 'Itens de suporte',
                'ordering': ['tipo_id', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(max_length=200)),
                ('usuario_email', models.EmailField(max_length=254)),
                ('usuario_setor', models.CharField(blank=True, max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField()),
                ('anexo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em andamento', 'Em andamento'), ('Resolvido', 'Resolvido'), ('Cancelado', 'Cancelado')], default='Aberto', max_length=20)),
                ('usuario_notificado', models.BooleanField(default=False)),
                ('responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('responsavel_solucao', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao_resolucao', models.TextField(blank=True, null=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='formularios.suporteitem')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='formularios.suportemotivo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='formularios.suportetipo')),
            ],
            options={
                'verbose_name': 'Chamado de suporte',
                'verbose_name_plural': 'Chamados de suporte',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
