# Generated by Django 5.0.6 on 2026-05-06 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_seed_catalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoSuporteTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamado_id', models.PositiveIntegerField(db_index=True)),
                ('tipo_evento', models.CharField(choices=[('comentario', 'Comentário')], default='comentario', max_length=30)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamado_suporte_timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timeline do chamado de suporte',
                'verbose_name_plural': 'Timeline dos chamados de suporte',
                'ordering': ['-data'],
            },
        ),
    ]
