# Generated by Django 5.0.6 on 2026-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_chamado_suporte_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadosuportetimeline',
            name='tipo_evento',
            field=models.CharField(choices=[('criado', 'Ticket criado'), ('etapa_alterada', 'Etapa alterada'), ('responsavel_alterado', 'Responsável alterado'), ('notificacao', 'Notificação ao solicitante'), ('comentario', 'Comentário')], default='comentario', max_length=30),
        ),
    ]
