# Generated by Django 5.2.10 on 2026-05-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_seed_easy_dashboards'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chamadosuporte',
            index=models.Index(fields=['usuario_email'], name='suporte_email_idx'),
        ),
        migrations.AddIndex(
            model_name='chamadosuporte',
            index=models.Index(fields=['tipo', 'status'], name='suporte_tipo_status_idx'),
        ),
        migrations.AddIndex(
            model_name='chamadosuporte',
            index=models.Index(fields=['-data_abertura'], name='suporte_aberta_desc_idx'),
        ),
    ]
