# Generated by Django 5.2.10 on 2026-07-06 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_add_chamado_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoSuporteResolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamado_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='suporte_resolucao/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamado_suporte_resolucoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolução de chamado de suporte',
                'verbose_name_plural': 'Resoluções de chamados de suporte',
            },
        ),
    ]
