# Generated by Django 5.2.10 on 2026-05-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_code',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Código de recuperação'),
        ),
    ]
