# Generated by Django 5.2.10 on 2026-05-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_recovery_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_code_expires_at',
            field=models.DateTimeField(blank=True, help_text='Quando null/passado, o código é considerado inválido.', null=True, verbose_name='Expiração do código de recuperação'),
        ),
    ]
