# Generated by Django 5.2.10 on 2026-05-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_recovery_code_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recovery_code_expires_at',
        ),
    ]
