# Generated by Django 5.2.10 on 2026-05-27 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, help_text='ID do tipo de relatório (ex.: metrics, sprint, cards). Resolve pra um gerador no REGISTRY.', max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('csv', 'CSV')], max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filtros aplicados (ex.: {sprint_id, period_start, period_end, user_id}).')),
                ('include_header', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('completed', 'Concluído'), ('failed', 'Falha')], db_index=True, default='pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='0–100')),
                ('progress_message', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório (Job)',
                'verbose_name_plural': 'Relatórios (Jobs)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='reports_rep_user_id_d828cc_idx')],
            },
        ),
    ]
